package mx.com.ols.fiscal.model.vo;

import java.util.Calendar;
import java.util.Date;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 24 13:06:26 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OlsSatClientsByPeriodVwImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public OlsSatClientsByPeriodVwImpl() {
    }

    /**
     * Returns the bind variable value for lstAnio.
     * @return bind variable value for lstAnio
     */
    public Integer getlstAnio() {
        return (Integer) getNamedWhereClauseParam("lstAnio");
    }

    /**
     * Sets <code>value</code> for bind variable lstAnio.
     * @param value value to bind as lstAnio
     */
    public void setlstAnio(Integer value) {
        setNamedWhereClauseParam("lstAnio", value);
    }

    /**
     * Returns the bind variable value for lstMes.
     * @return bind variable value for lstMes
     */
    public String getlstMes() {
        return (String) getNamedWhereClauseParam("lstMes");
    }

    /**
     * Sets <code>value</code> for bind variable lstMes.
     * @param value value to bind as lstMes
     */
    public void setlstMes(String value) {
        setNamedWhereClauseParam("lstMes", value);
    }
    
    @Override
    protected void executeQueryForCollection(Object qc, Object[] params, int numUserParams) {
        
        String lsWhere = "";
        if(getWhereClause() == null){
            lsWhere = " 1 = 2 ";
            
            Calendar fecha = Calendar.getInstance();
            int liAnio = fecha.get(Calendar.YEAR);
            int liMes = fecha.get(Calendar.MONTH) + 1;
            String lsYear = String.valueOf(liAnio);
            String lsMonth = getNomMes(liMes);
            //System.out.println("Valor inicial lsYear: "+lsYear);
            //System.out.println("Valor inicial lsMonth: "+lsMonth);
            setlstAnio(Integer.parseInt(lsYear));
            setlstMes(lsMonth);
            System.out.println("---------------------------------");
            //setNamedWhereClauseParam("lstAnio",lsYear);
            //setNamedWhereClauseParam("lstMes",lsMonth);
            
        }
        else{
            lsWhere = getWhereClause();
        }
        setWhereClause(lsWhere);        
        super.executeQueryForCollection(qc, params, numUserParams);
    }
    
    String getNomMes(int liNumMes){
        String lsReturn = "";
        if(liNumMes == 1){
            lsReturn = "ENERO";
        }
        if(liNumMes == 2){
            lsReturn = "FEBRERO";
        }
        if(liNumMes == 3){
            lsReturn = "MARZO";
        }
        if(liNumMes == 4){
            lsReturn = "ABRIL";
        }
        if(liNumMes == 5){
            lsReturn = "MAYO";
        }
        if(liNumMes == 6){
            lsReturn = "JUNIO";
        }
        if(liNumMes == 7){
            lsReturn = "JULIO";
        }
        if(liNumMes == 8){
            lsReturn = "AGOSTO";
        }
        if(liNumMes == 9){
            lsReturn = "SEPTIEMBRE";
        }
        if(liNumMes == 10){
            lsReturn = "OCTUBRE";
        }
        if(liNumMes == 11){
            lsReturn = "NOVIEMBRE";
        }
        if(liNumMes == 12){
            lsReturn = "DICIEMBRE";
        }
        return lsReturn;
    }
}

